### ISSUE TITLE
Can not open localhost in Firefox

### ISSUE THREAD

**Issue by kanintesova** [jeremycoder/nuxt-iam#1]
Great template!

I am not able to open it in Firefox. Chrome and Safari works fine.

I have also tried clearing cache in Firefox.

**Comment by kanintesova** [comment]
After a reboot and clearing all complete history in Firefox and restarting the server after that it now works.

**Comment by jeremycoder** [comment]
I'm glad it's working! Oh I'm sorry you had to clear your complete history. As long as Firefox can get data from a web site, then it should be able to get data from localhost. Awesome!
