### ISSUE TITLE
Wrong log message in line 199 of file /iam/misc/email.ts

### ISSUE THREAD

**Issue by oum100** [jeremycoder/nuxt-iam#3]
Line 199 is in function of "emailWithNodemailerSmtp". but log message in line 199 like this "Attempting to send mail using nodemailer-service".  So, just a bit confuse not a serious bug.  

Just fix it to be "Attempting to send mail using nodemailer-SMTP".  that it.

**Comment by oum100** [comment]
Just fix it to be "Attempting to send mail using nodemailer-SMTP". that it.

**Comment by jeremycoder** [comment]
@oum100 You're right, thanks. I updated it!
