### ISSUE TITLE
On Protected Page, when refreshed redirects to login page again.

### ISSUE THREAD

**Issue by andiamvinay** [jeremycoder/nuxt-iam#4]
1) Login to https://nuxtiam.com
2) Click on Protected Page
3) Refresh the browser

Expected : Should not redirect to the Login Page
Actual : Redirects to the login page again.

@jeremycoder

**Comment by jeremycoder** [comment]
Thank you. It looks like the Nuxt middleware isn't working very well. Will start to fix this.

**Comment by jeremycoder** [comment]
This issue should be fixed now.

**Comment by Syedimran98** [comment]
Hi jeremycoder,

Still I am facing same issue, its working fine on localhost but same issue I am also facing in network url. can you please tell me  what changes you did?
